title: Muhammad Adel Gabr - AI Portfolio
description: Machine Learning Engineer & Generative AI Specialist. Expert in LLM fine-tuning, RAG systems, and building scalable AI solutions.
author: Muhammad Adel Gabr
url: https://muhammadadelgabr.github.io
baseurl: ""

# SEO settings
lang: en_US
locale: en_US

# Social media
social:
  name: Muhammad Adel Gabr
  links:
    - https://www.linkedin.com/in/muhammadadelgabr/
    - https://github.com/muhammadadelgabr/
    - https://www.huggingface.co/muhammadadelgabr/

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .DS_Store

# Include files
include:
  - assets
  - .htaccess

# Markdown settings
markdown: kramdown
highlighter: rouge

# Compression
sass:
  style: compressed

# SEO and meta tags
twitter:
  username: muhammadadelgabr

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Theme (default GitHub Pages theme)
theme: minima 